Términos y Condiciones
-Declaración Jurada-

Por la presente manifiesto voluntaria y expresamente y a todos sus efectos legales, lo siguiente: 
a) Que tengo pleno y absoluto conocimiento de la peligrosidad potencial que representa la participación en competencias deportivas y especialmente, los inherentes a la presente, asumiendo sus consecuencias en forma exclusiva y excluyente, sin excepción alguna. 
b) Que he efectuado previamente, en forma privada, la totalidad de los controles clínicos indicados y el entrenamiento respectivo, dejando constancia de encontrarme plenamente apto para participar en la competencia, conforme a los resultados obtenidos y al diagnostico médico. 
c) Que no obstante lo manifestado en el inciso a)de la presente, a modo exclusivamente enunciativo, con fines ampliatorios y sin que ello lo limite y/o modifique en modo alguno, expreso que se hallan incluídos en los riesgos que he asumido: caídas, contactos con otros participantes y/o con Autoridades de la prueba y/o Personal de Seguridad y/o vehículos de cualquier tipo y/o publico asistente, etc; fenómenos climáticos (tormentas eléctricas, granizo, lluvia, cambios de temperatura, humedad, etc.) 
d) Que me comprometo a aceptar toda decisión que pudiera adoptarse a mi respecto, por parte de las Autoridades de la competencia, vinculada con mi capacidad para completar con seguridad la prueba, renunciando por este acto a toda oposición a lo que pudiera disponerse. 
e) Que he leído y aceptado, los términos y condiciones contenidas en el Reglamento aplicable a la competencia , que incluye la presente manifestación voluntaria de deslinde de responsabilidades emergentes. 
f) Que autorizo puntualmente por la presente, para cualquier uso legítimo, a la Organización de la prueba, Sponsors y / o a cualquier otra persona y /p Institución vinculada a los mismos, al uso de mi imagen , eventual y/o expresamente captada a través de fotografías, películas, videos, grabaciones, y / o cualquier otro medio técnico de registración del evento, en forma incondicional y gratuita, renunciando a toda acción y /o derecho que pudiera ejercer, tendiente a lograr compensaciones por ello. 
g) Que, concordante con la Responsabilidad plena, total y excluyente , que asumo por esta declaración, efectuada en mi propio nombre y / o en el de cualquier persona que pudiera ejercer mi representación, invocando presuntos derechos, dispenso sin excepciones a los Organizadores de la prueba y/o voluntarios y/o Sponsors y/o colaboradores de todo tipo y/o a sus representantes y/o sucesores, etc.; por cualquier tipo de consecuencia emergente de mi participación en este evento, aún cuando las mismas pudieran eventualmente imputarse a culpa y/o negligencia por parte de las personas dispensadas"